/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: rickyfunkel (https://sketchfab.com/rickyfunkel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cool-dude-02981747d86c4f1f9c662171f4ce3a68
Title: Cool Dude
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function HeroChracter(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/cool_dude.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="8127f3a4e80c4eaaaf3e9380348c0d06fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Emitter" rotation={[Math.PI / 2, 0, 0]}>
                  <group
                    name="Sphere_2"
                    position={[-249.984, -139.259, -278.289]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.013}>
                    <mesh
                      name="Sphere_2_particle3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_particle3_0.geometry}
                      material={materials.particle3}
                    />
                  </group>
                  <group
                    name="Sphere_1"
                    position={[152.878, 139.84, -264.75]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.012}>
                    <mesh
                      name="Sphere_1_particle2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_1_particle2_0.geometry}
                      material={materials.particle2}
                    />
                  </group>
                  <group
                    name="Sphere"
                    position={[132.193, -64.22, -255.036]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.011}>
                    <mesh
                      name="Sphere_particle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_particle_0.geometry}
                      material={materials.particle}
                    />
                  </group>
                  <group
                    name="Sphere_2_2"
                    position={[-3.317, -113.829, -236.123]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.014}>
                    <mesh
                      name="Sphere_2_2_particle3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_2_particle3_0.geometry}
                      material={materials.particle3}
                    />
                  </group>
                  <group
                    name="Sphere_1_2"
                    position={[-33.481, 29.469, -223.588]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.014}>
                    <mesh
                      name="Sphere_1_2_particle2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_1_2_particle2_0.geometry}
                      material={materials.particle2}
                    />
                  </group>
                  <group
                    name="Sphere_2_3"
                    position={[193.526, 180.889, -205.949]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.012}>
                    <mesh
                      name="Sphere_2_3_particle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_3_particle_0.geometry}
                      material={materials.particle}
                    />
                  </group>
                  <group
                    name="Sphere_2_4"
                    position={[-215.688, 158.91, -192.277]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.01}>
                    <mesh
                      name="Sphere_2_4_particle3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_4_particle3_0.geometry}
                      material={materials.particle3}
                    />
                  </group>
                  <group
                    name="Sphere_1_3"
                    position={[248.206, -153.268, -177.322]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.013}>
                    <mesh
                      name="Sphere_1_3_particle2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_1_3_particle2_0.geometry}
                      material={materials.particle2}
                    />
                  </group>
                  <group
                    name="Sphere_3"
                    position={[41.876, -176.92, -157.985]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.009}>
                    <mesh
                      name="Sphere_3_particle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_3_particle_0.geometry}
                      material={materials.particle}
                    />
                  </group>
                  <group
                    name="Sphere_2_5"
                    position={[132.499, 46.708, -147.115]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.012}>
                    <mesh
                      name="Sphere_2_5_particle3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_5_particle3_0.geometry}
                      material={materials.particle3}
                    />
                  </group>
                  <group
                    name="Sphere_1_4"
                    position={[-248.638, -171.002, -128.084]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.013}>
                    <mesh
                      name="Sphere_1_4_particle2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_1_4_particle2_0.geometry}
                      material={materials.particle2}
                    />
                  </group>
                  <group
                    name="Sphere_4"
                    position={[-240.23, 79.016, -114.202]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.013}>
                    <mesh
                      name="Sphere_4_particle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_4_particle_0.geometry}
                      material={materials.particle}
                    />
                  </group>
                  <group
                    name="Sphere_2_6"
                    position={[-200.871, 55.402, -102.288]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.009}>
                    <mesh
                      name="Sphere_2_6_particle3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_6_particle3_0.geometry}
                      material={materials.particle3}
                    />
                  </group>
                  <group
                    name="Sphere_1_5"
                    position={[147.086, 109.473, -84.806]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.011}>
                    <mesh
                      name="Sphere_1_5_particle2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_1_5_particle2_0.geometry}
                      material={materials.particle2}
                    />
                  </group>
                  <group
                    name="Sphere_5"
                    position={[-48.399, 153.915, -71.456]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.01}>
                    <mesh
                      name="Sphere_5_particle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_5_particle_0.geometry}
                      material={materials.particle}
                    />
                  </group>
                  <group
                    name="Sphere_2_7"
                    position={[-235.18, -158.57, -53.493]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.012}>
                    <mesh
                      name="Sphere_2_7_particle3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_7_particle3_0.geometry}
                      material={materials.particle3}
                    />
                  </group>
                  <group
                    name="Sphere_1_6"
                    position={[48.628, 187.723, -38.976]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.012}>
                    <mesh
                      name="Sphere_1_6_particle2_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_1_6_particle2_0.geometry}
                      material={materials.particle2}
                    />
                  </group>
                  <group
                    name="Sphere_6"
                    position={[73.761, 123.198, -29.925]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.009}>
                    <mesh
                      name="Sphere_6_particle_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_6_particle_0.geometry}
                      material={materials.particle}
                    />
                  </group>
                  <group
                    name="Sphere_2_8"
                    position={[-115.657, 207.743, -11.794]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.008}>
                    <mesh
                      name="Sphere_2_8_particle3_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Sphere_2_8_particle3_0.geometry}
                      material={materials.particle3}
                    />
                  </group>
                </group>
                <group name="floor">
                  <mesh
                    name="floor_floor_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.floor_floor_0.geometry}
                    material={materials.floor}
                  />
                </group>
                <group name="hat" position={[0, 6.683, 9.975]} scale={0.49}>
                  <group name="Object_46">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_49"
                      geometry={nodes.Object_49.geometry}
                      material={materials.cool_hat}
                      skeleton={nodes.Object_49.skeleton}
                    />
                    <group name="Object_48" position={[0, 160.478, 9.975]} scale={0.49} />
                    <group name="hat_3" />
                  </group>
                </group>
                <group name="cool_dud" position={[0, 0, 8.807]} scale={0.098}>
                  <group name="RIG">
                    <group name="Object_56">
                      <primitive object={nodes._rootJoint_1} />
                      <skinnedMesh
                        name="Object_149"
                        geometry={nodes.Object_149.geometry}
                        material={materials.cool_head}
                        skeleton={nodes.Object_149.skeleton}
                      />
                      <skinnedMesh
                        name="Object_151"
                        geometry={nodes.Object_151.geometry}
                        material={materials.cool_eyes}
                        skeleton={nodes.Object_151.skeleton}
                      />
                      <skinnedMesh
                        name="Object_153"
                        geometry={nodes.Object_153.geometry}
                        material={materials.cool_eyes}
                        skeleton={nodes.Object_153.skeleton}
                      />
                      <skinnedMesh
                        name="Object_155"
                        geometry={nodes.Object_155.geometry}
                        material={materials.cool_jacket}
                        skeleton={nodes.Object_155.skeleton}
                      />
                      <skinnedMesh
                        name="Object_157"
                        geometry={nodes.Object_157.geometry}
                        material={materials.cool_hands}
                        skeleton={nodes.Object_157.skeleton}
                      />
                      <skinnedMesh
                        name="Object_159"
                        geometry={nodes.Object_159.geometry}
                        material={materials.cool_pants}
                        skeleton={nodes.Object_159.skeleton}
                      />
                      <skinnedMesh
                        name="Object_161"
                        geometry={nodes.Object_161.geometry}
                        material={materials.cool_shoes}
                        skeleton={nodes.Object_161.skeleton}
                      />
                      <group name="Object_148" position={[0, 129.731, 12.674]} scale={0.49} />
                      <group
                        name="Object_150"
                        position={[7.014, 130.187, 22.625]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.49}
                      />
                      <group
                        name="Object_152"
                        position={[-7.014, 130.187, 22.625]}
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.49}
                      />
                      <group name="Object_154" position={[0, 82.254, 3.409]} scale={0.49} />
                      <group name="Object_156" position={[0, 93.018, 0.496]} scale={0.49} />
                      <group name="Object_158" position={[0, 31.09, 3.55]} scale={0.49} />
                      <group name="Object_160" position={[0, -0.112, 2.109]} scale={0.49} />
                    </group>
                  </group>
                  <group name="CONTROLS">
                    <group
                      name="cog"
                      position={[0, 54.999, 8.833]}
                      rotation={[1.553, 0, 0]}
                      scale={2.043}>
                      <group name="hips" rotation={[-0.198, 0, 0]} />
                      <group
                        name="chest_2"
                        position={[0, -2.139, 3.303]}
                        rotation={[0.006, 0.224, 0.407]}>
                        <group
                          name="neck_2"
                          position={[0, 0.965, -23.737]}
                          rotation={[0.827, -0.193, -0.16]}
                          scale={0.155}>
                          <group
                            name="head_2"
                            position={[1.761, -6.617, -14.249]}
                            rotation={[0.543, 0.074, 0.157]}
                          />
                        </group>
                      </group>
                    </group>
                    <group
                      name="L_arm_2"
                      position={[4.799, 102.705, 9.733]}
                      rotation={[1.27, 1.117, -0.694]}
                      scale={0.106}>
                      <group name="L_wrist_Goal" />
                    </group>
                    <group
                      name="R_arm_2"
                      position={[-6.158, 79.415, 6.514]}
                      rotation={[-1.065, 0.223, -2.777]}
                      scale={0.517}>
                      <group name="R_wrist_Goal" />
                    </group>
                    <group
                      name="L_leg_2"
                      position={[47.016, 38.193, -17.685]}
                      rotation={[-1.47, 0, Math.PI]}
                      scale={2.043}
                    />
                    <group
                      name="R_leg_2"
                      position={[-14.498, 63.722, 5.702]}
                      rotation={[1.672, 0, 0.95]}
                      scale={2.269}
                    />
                  </group>
                  <group name="GEO">
                    <group name="head_3" position={[0, 265.023, 25.892]} />
                    <group
                      name="eyes"
                      position={[0, 265.955, 46.219]}
                      rotation={[Math.PI / 2, 0, 0]}>
                      <group name="L_eye_2" position={[14.329, 0, 0]} />
                      <group name="R_eye_2" position={[-14.329, 0, 0]} />
                    </group>
                    <group
                      name="cig"
                      position={[4.029, 253.209, 56.698]}
                      rotation={[-2.615, -1.404, 0.546]}
                      scale={2.043}>
                      <group
                        name="cig_2"
                        position={[0, 0.193, -7.64]}
                        rotation={[-3.064, 0, 0]}
                        scale={0.49}>
                        <mesh
                          name="cig_2_cool_cig_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.cig_2_cool_cig_0.geometry}
                          material={materials.cool_cig}
                        />
                      </group>
                      <group
                        name="smoke"
                        position={[0.012, -3.461, -11.371]}
                        rotation={[-3.064, 0, 0]}
                        scale={0.49}>
                        <mesh
                          name="smoke_cool_smoke_0"
                          castShadow
                          receiveShadow
                          geometry={nodes.smoke_cool_smoke_0.geometry}
                          material={materials.cool_smoke}
                        />
                      </group>
                    </group>
                    <group name="jacket" position={[0, 168.034, 6.964]} />
                    <group name="hands" position={[0, 190.023, 1.013]} />
                    <group name="pants" position={[0, 92.598, -72.069]} />
                    <group name="shoes" position={[0, -0.228, 4.308]} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cool_dude.glb')


